name: Build firmware

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up dependencies
      run: |
        sudo apt update
        sudo apt install cmake gcc-arm-none-eabi build-essential libnewlib-arm-none-eabi -y

    - name: Clone Pico SDK
      run: |
        git clone https://github.com/raspberrypi/pico-sdk.git
        echo "PICO_SDK_PATH=$PWD/pico-sdk" >> $GITHUB_ENV

    - name: Build firmware
      run: |
        mkdir build
        cd build
        cmake .. -DPICO_SDK_PATH=$PICO_SDK_PATH
        make

    - name: Upload UF2
      uses: actions/upload-artifact@v3
      with:
        name: mclk.uf2
        path: build/mclk.uf2
